import { writable, derived } from "svelte/store";

// JSON (バンドル) は言語中立。言語はこのラベル層だけで切り替える (docs/design/web.md)。
export const lang = writable("ja");

const DICT = {
  ja: {
    title: "ダイヤ改正 意味的差分レポート",
    old_gen: "旧世代", new_gen: "新世代", generated: "生成日時",
    summary: "1. 全体サマリ", routes: "2. 路線別詳細", stops: "3. 停留所の変更",
    validation: "4. データ検証", unchanged_routes: "変更のない路線",
    unchanged_note: "以下の路線では路線・運行パターン・便数時刻の変化は検出されていない。",
    major_changes: "主要変更 (major)", event: "イベント", count: "件数",
    type: "種別", target: "対象", description: "内容",
    route: "路線", families: "構成系統", trips: "便数", cohesion: "凝集度",
    branch_note: "枝線構造: 系統ごとに経路が大きく異なる",
    structure: "運行系統の構成 (停車地がほぼ重ならない系統が同居)",
    band_table: "時間帯別本数 (旧→新)", direction: "方向", day: "曜日", total: "計",
    outbound: "往路", inbound: "復路",
    weekday: "平日", saturday: "土曜", sunday_holiday: "日祝", weekend: "土日",
    daily: "毎日", irregular: "特定日",
    evidence: "根拠データ (RawDiff)", quantification: "数値詳細",
    timetable: "発車時刻表 (始発停留所基準)", map: "地図",
    pattern_change: "停車パターン変化", old: "旧", new: "新",
    file: "ファイル", kind: "種別", key: "キー", column: "カラム",
    old_value: "旧値", new_value: "新値",
    more_rows: (n) => `…ほか ${n} 件`,
    explained_ratio: "説明被覆率 (explained_ratio)",
    residual_all: "未説明の残差 (全件)", no_residual: "未説明の残差はない (全 RawDiff が説明済み)。",
    stops_count: "停", trips_count: "便",
    close: "閉じる", open_detail: "詳細 ▸", close_detail: "詳細 ▾",
    no_data: "データがありません。gtfs-semdiff compare --html で生成された HTML を開いてください。",
    id_churn: "ID 張り替え (意味変化なし)",
    added_stop: "新設", removed_stop: "廃止", matched_stop: "継続",
    attribution_note: "地図: 国土地理院タイル",
  },
  en: {
    title: "GTFS semantic diff report",
    old_gen: "Old", new_gen: "New", generated: "Generated",
    summary: "1. Summary", routes: "2. Routes", stops: "3. Stop changes",
    validation: "4. Data validation", unchanged_routes: "Unchanged routes",
    unchanged_note: "No route, pattern, or service-level changes were detected on these routes.",
    major_changes: "Major changes", event: "Event", count: "Count",
    type: "Type", target: "Target", description: "Description",
    route: "Route", families: "Sub-routes", trips: "Trips", cohesion: "Cohesion",
    branch_note: "Branch structure: sub-routes serve mostly different corridors",
    structure: "Service branches (mostly disjoint stop sequences)",
    band_table: "Trips per time band (old→new)", direction: "Dir", day: "Days", total: "Total",
    outbound: "Outbound", inbound: "Inbound",
    weekday: "Weekday", saturday: "Saturday", sunday_holiday: "Sun/Hol", weekend: "Weekend",
    daily: "Daily", irregular: "Irregular",
    evidence: "Evidence (raw diffs)", quantification: "Quantification",
    timetable: "Departures (at first stop)", map: "Map",
    pattern_change: "Stop pattern change", old: "old", new: "new",
    file: "File", kind: "Kind", key: "Key", column: "Column",
    old_value: "Old", new_value: "New",
    more_rows: (n) => `…and ${n} more`,
    explained_ratio: "Explained ratio",
    residual_all: "Unexplained residual (all)", no_residual: "No unexplained residual.",
    stops_count: "stops", trips_count: "trips",
    close: "Close", open_detail: "Details ▸", close_detail: "Details ▾",
    no_data: "No data. Open an HTML generated by gtfs-semdiff compare --html.",
    id_churn: "Technical ID churn",
    added_stop: "added", removed_stop: "removed", matched_stop: "kept",
    attribution_note: "Map: GSI tiles",
  },
};

export const t = derived(lang, ($lang) => (key, ...args) => {
  const v = DICT[$lang][key] ?? DICT.ja[key] ?? key;
  return typeof v === "function" ? v(...args) : v;
});

export function eventName(catalog, type, language) {
  const entry = catalog?.[type];
  if (!entry) return type;
  return language === "en" ? entry.en : entry.ja;
}
